# Generated by Django 4.1 on 2022-09-01 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='sub_content',
            field=models.CharField(max_length=70),
        ),
    ]
